version: '3.9'
services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/docker/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - nginx-php81-postgres

  php82-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php82
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php81-postgres

  postgres-service:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/tmp
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - nginx-php81-postgres

networks:
  nginx-php81-postgres:
